export default [
  {
    files: ["app.js", "sw.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        fetch: "readonly",
        alert: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        Date: "readonly",
        Number: "readonly",
        Math: "readonly",
        String: "readonly",
        console: "readonly",
        Notification: "readonly",
        Intl: "readonly",
        URL: "readonly",
        Promise: "readonly",
        // Service Worker globals
        self: "readonly",
        caches: "readonly",
        Response: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" }],
      "no-undef": "error",
      "no-const-assign": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-unreachable": "warn",
      "no-constant-condition": "warn",
      "eqeqeq": ["warn", "smart"],
      "no-var": "warn",
      "prefer-const": ["warn", { destructuring: "all" }],
      "no-throw-literal": "warn",
      "no-self-compare": "warn",
      "no-template-curly-in-string": "warn",
    },
  },
];
